name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # 1. Continuous Integration (Test & Build)
  ci:
    name: CI - Lint, Typecheck, Build
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "postgresql://dummy:dummy@localhost:5432/dummy"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Lint & Type Check
        run: bun run lint && bun run check-types

      - name: Build
        run: bun run build

  # 2. Continuous Deployment (Deploy to Production)
  cd:
    name: CD - Deploy to Production
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_PASSWORD }}
          envs: POSTGRES_USER,POSTGRES_PASSWORD,POSTGRES_DB,JWT_SECRET,VITE_API_URL
          script: |
            if [ ! -d "app" ]; then
              echo "Cloning repository..."
              git clone https://github.com/vasantkr97/Orch8.git app
            fi
            # Go to app directory
            cd app
            
            # Pull latest changes
            echo "Pulling latest changes..."
            git checkout main
            git pull origin main
            
            # Create/Update .env file from GitHub Secrets
            echo "Generating .env file..."
            echo "POSTGRES_USER=$POSTGRES_USER" > .env
            echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
            echo "POSTGRES_DB=$POSTGRES_DB" >> .env
            echo "JWT_SECRET=$JWT_SECRET" >> .env
            echo "VITE_API_URL=$VITE_API_URL" >> .env
            
            # Deploy
            echo "Deploying..."
            docker compose build
            docker compose up -d postgres
            echo "Waiting for DB..."
            sleep 5
            docker compose run --rm backend bunx prisma migrate deploy --config=./packages/db/prisma.config.ts
            docker compose up -d
            
            echo "Deployment Complete!"
